package com.rentease.main;

import com.rentease.main.Daftar;
import com.rentease.main.Login;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import com.rentease.database.DatabaseConnection;
import static com.rentease.database.Session.currentLogin;
import java.sql.*;
import javax.swing.JLabel;

public class Login extends javax.swing.JFrame {    
    private Point mouseDownCompCoords = null;
    
    public Login() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        
        
          // Tambahkan listener mouse pressed
    addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
            // Mendapatkan posisi awal saat mouse ditekan
            mouseDownCompCoords = e.getPoint();
        }
    });

    // Tambahkan listener mouse dragged
    addMouseMotionListener(new MouseMotionAdapter() {
        @Override
        public void mouseDragged(MouseEvent e) {
            // Menghitung perbedaan posisi mouse saat ini dengan posisi awal saat mouse ditekan
            try {
                int x = getLocation().x + e.getX() - mouseDownCompCoords.x;
                int y = getLocation().y + e.getY() - mouseDownCompCoords.y;
                setLocation(x, y);
            } catch (Exception ex) {
            }
        }
    });
    
    form_Login1.getDaftarLabel().addMouseListener(new MouseAdapter() {
    @Override
    public void mousePressed(MouseEvent e) {
        // Panggil method untuk beralih ke frame selanjutnya saat label DaftarL ditekan
        navigateToNextFrame();
    }
});
    
    form_Login1.getUbahLabel().addMouseListener(new MouseAdapter() {
    @Override
    public void mousePressed(MouseEvent e) {
        // Panggil method untuk beralih ke frame selanjutnya saat label DaftarL ditekan
        navigateToUbahSandi();
    }
    });
    form_Login1.getMasukButton().addMouseListener(new MouseAdapter() {
    @Override
    public void mousePressed(MouseEvent e) {
        JLabel notif = form_Login1.setNotif();
        try
        {
            Connection con = DatabaseConnection.getConnection();
            Statement stm = con.createStatement();
            
            String username = form_Login1.getUsername();
            char[] passwordChar = form_Login1.getPassword();
            String password = new String(passwordChar);
            
            if (username.isEmpty() || password.isEmpty()) {
                notif.setText("                       Data tidak lengkap!");
                notif.setForeground(Color.red);
            } else {          
                String sql = "SELECT * FROM t_users WHERE username='"+ username + "' AND password = '" + password + "'";
                ResultSet rs = stm.executeQuery(sql);

                if(rs.next()){
                    //  if username and password is right then go to homepage
                    currentLogin = username;
                    System.out.println("Berhasil Login! Username: " + currentLogin);                
                    navigateToDashboard();
                } else {
                    //  is username and pass is wrong
                    notif.setText("         Nama Pengguna Atau Kata Sandi Salah");
                    notif.setForeground(Color.red);
                }
            }
  
        }
        catch(SQLException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
});
    
}
    
    private void navigateToNextFrame() {
        Daftar nextFrame = new Daftar();
        nextFrame.setVisible(true);
        dispose();
    }

     private void navigateToUbahSandi() {
         UbahSandi ubah = new UbahSandi();
         ubah.setVisible(true);
         dispose();
    }
    private void navigateToDashboard() {
        Dashboard masuk = new Dashboard();
        masuk.setVisible(true);
        dispose();
    }


 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new com.rentease.swing.RoundPanel();
        form_Login1 = new com.rentease.form.Form_Login();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Login"); // NOI18N
        setUndecorated(true);

        roundPanel1.setBackground(new java.awt.Color(36, 37, 41));

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(form_Login1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(form_Login1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login panel = new Login();
            
                panel.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rentease.form.Form_Login form_Login1;
    private com.rentease.swing.RoundPanel roundPanel1;
    // End of variables declaration//GEN-END:variables
}
